### ISSUE TITLE
Error with recalculate when fetching weather

### ISSUE THREAD

**Issue by dagalufh** [dagalufh/TellstickNode#42]
[Core.log]  06:00:17:695,Recalculate,Fetching weather information.
events.js:85
throw er; // Unhandled 'error' event
^
Error: connect ETIMEDOUT
at exports._errnoException (util.js:746:11)
at TCPConnectWrap.afterConnect [as oncomplete](net.js:983:19)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
[Core.log]  06:02:39:613,Bootprocess,####################################

Below is from user errorlog.
Need to add a error handling om that part.

**Comment by dagalufh** [comment]
Fixed in 2.1.5<
